[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.2.4", features = ["web"] }
futures = "0.3"
gloo-timers = "0.2.4"
pin-utils = "0.1"
use-epic = { path = "../use-epic" }
